import {
	Activity,
	Atom,
	AudioWaveform,
	Axe,
	BicepsFlexed,
	BookOpen,
	Bot,
	Box,
	Boxes,
	Bug,
	Camera,
	Circle,
	Cloud,
	Code,
	Command,
	CreditCard,
	Database,
	Egg,
	FlaskConical,
	GalleryVerticalEnd,
	Gem,
	Handshake,
	Hexagon,
	Lightbulb,
	Mic,
	Mountain,
	Network,
	Octagon,
	Paintbrush,
	PartyPopper,
	Pentagon,
	Rocket,
	Scan,
	Scroll,
	Send,
	Shield,
	Smile,
	Square,
	SquareDashed,
	SquareTerminal,
	Sword,
	TentTree,
	ThumbsUp,
	Triangle,
	User,
	Wallet,
	WandSparkles,
	Zap,
} from 'lucide-react';

export const ICONS = {
	circle: Circle,
	square: Square,
	triangle: Triangle,
	pentagon: Pentagon,
	hexagon: Hexagon,
	octagon: Octagon,
	egg: Egg,
	shield: Shield,
	squareDashed: SquareDashed,
	scan: Scan,
	lightBulb: Lightbulb,
	flaskConical: FlaskConical,
	atom: Atom,
	database: Database,
	box: Box,
	boxes: Boxes,
	network: Network,
	activity: Activity,
	handshake: Handshake,
	wallet: Wallet,
	creditCard: CreditCard,
	user: User,
	bug: Bug,
	cloud: Cloud,
	send: Send,
	camera: Camera,
	mic: Mic,
	wandSparkles: WandSparkles,
	paintbrush: Paintbrush,
	code: Code,
	gem: Gem,
	rocket: Rocket,
	scroll: Scroll,
	zap: Zap,
	bicepsFlexed: BicepsFlexed,
	smile: Smile,
	partyPopper: PartyPopper,
	thumbsUp: ThumbsUp,
	axe: Axe,
	sword: Sword,
	mountain: Mountain,
	tentTree: TentTree,
	galleryVerticalEnd: GalleryVerticalEnd,
	command: Command,
	audioWaveform: AudioWaveform,
	squareTerminal: SquareTerminal,
	bot: Bot,
	bookOpen: BookOpen,
} as const;
